baseurl = "" # Include trailing slash (somehow, doesn't work in Netlify if non-empty)
title = "NightBlue"
author = "Weru"
canonifyurls = true
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[permalinks]
pages = ':contentbasename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
